requests:
    - name: "first"
      frequency: "10 * * * *"
      file: "script.sh"
      run: |
        ping google.com
cloud:
    provider: "aws"
    credentials: "~/.aws/credentials"
    profile: "default"
    region: "default"
api-server:
    host: "http://localhost:8080"