spring:
    server:
        port : 10075
    main:
        banner-mode: off
        web-environment: false
        web-application-type: NONE
    profiles:
        active: prod

logging:
    level:
        root: OFF

endpoints:
    shutdown:
        sensetive: false
        enabled: true
