---
example: true # remove this line for usage
project:
        name: “example”
requests:
        tag(optional): “first”,
        host: “http://localhost:8080”
        pathes: [“/ping”]
cloud:
        provider: "aws"
        credentials: "~/.aws/credentials"
        profile: "default"
        region: "default"
mailing:
        email: test@gmail.com
scheduler:
        frequency: 5(m|d|w|s)
---
