openapi: 3.0.1
info:
  title: OpenAPI document of ResourceTracker API Server
  description: ResourceTracker API Server Open API documentation
  version: "1.0"

tags:
  - name: TopicResource
    description: Contains all endpoints related to specific topics and their data filtering
  - name: TerraformResource
    description: Contains endpoints related to Terraform deployment operations
  - name: ValidationResource
    description: Contains all endpoints related to both data validation and its further retrieval.

paths:
  /v1/topic/logs:
    get:
      tags:
        - TopicResource
      responses:
        200:
          description: Current resource state is successfully retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TopicLogsResult"
  /v1/terraform/apply:
    post:
      tags:
        - TerraformResource
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TerraformDeploymentApplication"
      responses:
        201:
          description: New remote infrastructure was successfully deployed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TerraformDeploymentApplicationResult"
        400:
          description: Given deployment application contains incorrect data
  /v1/terraform/destroy:
    post:
      tags:
        - TerraformResource
      requestBody:
        required: true
        description: Destroys new Terraform infrastructure
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TerraformDestructionApplication"
      responses:
        201:
          description: Deployed remote infrastructure is successfully destroyed
        400:
          description: Given destruction application contains incorrect data
  /v1/credentials/acquire:
    post:
      tags:
        - ValidationResource
      requestBody:
        required: true
        description: Checks if the given credentials file contains correct data
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/ValidationCredentialsApplication"
      responses:
        201:
          description: Given credentials file is confirmed to be correct
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationCredentialsApplicationResult"
        400:
          description: Given script application contains incorrect data
  /v1/script/acquire:
    post:
      tags:
        - ValidationResource
      requestBody:
        required: true
        description: Checks if the given script file contains allowed data
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/ValidationScriptApplication"
      responses:
        201:
          description: Given script file is confirmed to be correct
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationScriptApplicationResult"
        400:
          description: Given script application contains incorrect data

components:
  schemas:
    TopicLogsResult:
      required:
        - result
      properties:
        result:
          type: array
          items:
            $ref: "#/components/schemas/TopicLogsUnit"
    TopicLogsUnit:
      required:
        - id
        - data
        - error
        - hostname
        - hostaddress
        - timestamp
      properties:
        id:
          type: string
          format: uuid
        data:
          type: string
        error:
          type: string
        hostname:
          type: string
        hostaddress:
          type: string
        timestamp:
          type: string
          format: timestamp
    TerraformDeploymentApplication:
      required:
        - requests
        - provider
        - credentials
      properties:
        requests:
          type: array
          items:
            $ref: "#/components/schemas/DeploymentRequest"
        provider:
          $ref: "#/components/schemas/Provider"
        credentials:
          oneOf:
            - $ref: "#/components/schemas/AWSCredentials"
    DeploymentRequest:
      required:
        - name
        - script
        - frequency
      properties:
        name:
          type: string
        script:
          type: string
        frequency:
          type: string
          pattern: "(((([0-9]|[0-5][0-9])(-([0-9]|[0-5][0-9]))?,)*([0-9]|[0-5][0-9])(-([0-9]|[0-5][0-9]))?)|(([\\*]|[0-9]|[0-5][0-9])/([0-9]|[0-5][0-9]))|([\\?])|([\\*]))[\\s](((([0-9]|[0-5][0-9])(-([0-9]|[0-5][0-9]))?,)*([0-9]|[0-5][0-9])(-([0-9]|[0-5][0-9]))?)|(([\\*]|[0-9]|[0-5][0-9])/([0-9]|[0-5][0-9]))|([\\?])|([\\*]))[\\s](((([0-9]|[0-1][0-9]|[2][0-3])(-([0-9]|[0-1][0-9]|[2][0-3]))?,)*([0-9]|[0-1][0-9]|[2][0-3])(-([0-9]|[0-1][0-9]|[2][0-3]))?)|(([\\*]|[0-9]|[0-1][0-9]|[2][0-3])/([0-9]|[0-1][0-9]|[2][0-3]))|([\\?])|([\\*]))[\\s](((([1-9]|[0][1-9]|[1-2][0-9]|[3][0-1])(-([1-9]|[0][1-9]|[1-2][0-9]|[3][0-1]))?,)*([1-9]|[0][1-9]|[1-2][0-9]|[3][0-1])(-([1-9]|[0][1-9]|[1-2][0-9]|[3][0-1]))?(C)?)|(([1-9]|[0][1-9]|[1-2][0-9]|[3][0-1])/([1-9]|[0][1-9]|[1-2][0-9]|[3][0-1])(C)?)|(L(-[0-9])?)|(L(-[1-2][0-9])?)|(L(-[3][0-1])?)|(LW)|([1-9]W)|([1-3][0-9]W)|([\\?])|([\\*]))[\\s](((([1-9]|0[1-9]|1[0-2])(-([1-9]|0[1-9]|1[0-2]))?,)*([1-9]|0[1-9]|1[0-2])(-([1-9]|0[1-9]|1[0-2]))?)|(([1-9]|0[1-9]|1[0-2])/([1-9]|0[1-9]|1[0-2]))|(((JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)(-(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC))?,)*(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)(-(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC))?)|((JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)/(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC))|([\\?])|([\\*]))[\\s]((([1-7](-([1-7]))?,)*([1-7])(-([1-7]))?)|([1-7]/([1-7]))|(((MON|TUE|WED|THU|FRI|SAT|SUN)(-(MON|TUE|WED|THU|FRI|SAT|SUN))?,)*(MON|TUE|WED|THU|FRI|SAT|SUN)(-(MON|TUE|WED|THU|FRI|SAT|SUN))?(C)?)|((MON|TUE|WED|THU|FRI|SAT|SUN)/(MON|TUE|WED|THU|FRI|SAT|SUN)(C)?)|(([1-7]|(MON|TUE|WED|THU|FRI|SAT|SUN))?(L|LW)?)|(([1-7]|MON|TUE|WED|THU|FRI|SAT|SUN)#([1-7])?)|([\\?])|([\\*]))([\\s]?(([\\*])?|(19[7-9][0-9])|(20[0-9][0-9]))?| (((19[7-9][0-9])|(20[0-9][0-9]))/((19[7-9][0-9])|(20[0-9][0-9])))?| ((((19[7-9][0-9])|(20[0-9][0-9]))(-((19[7-9][0-9])|(20[0-9][0-9])))?,)*((19[7-9][0-9])|(20[0-9][0-9]))(-((19[7-9][0-9])|(20[0-9][0-9])))?)?)"
    Provider:
      type: string
      enum:
        - aws
    AWSCredentials:
      required:
        - accessKey
        - secretKey
        - profile
        - region
      properties:
        accessKey:
          type: string
        secretKey:
          type: string
        profile:
          type: string
        region:
          type: string
    TerraformDeploymentApplicationResult:
      required:
        - machineAddress
      properties:
        machineAddress:
          type: string
    TerraformDestructionApplication:
      required:
        - requests
        - provider
        - credentials
      properties:
        requests:
          type: array
          items:
            $ref: "#/components/schemas/DestructionRequest"
        provider:
          $ref: "#/components/schemas/Provider"
        credentials:
          oneOf:
            - $ref: "#/components/schemas/AWSCredentials"
    DestructionRequest:
      required:
        - name
      properties:
        name:
          type: string
    ValidationCredentialsApplication:
      required:
        - file
      properties:
        file:
          type: string
          format: base64
    ValidationCredentialsApplicationResult:
    ValidationScriptApplication:
      required:
        - file
      properties:
        file:
          type: string
          format: base64
    ValidationScriptApplicationResult:
