openapi: 3.0.1
info:
  title: OpenAPI document of ResourceTracker API Server
  description: ResourceTracker API Server Open API documentation
  version: "1.0"

tags:
  - name: TopicResource
    description: Contains all endpoints related to specific topics and their data filtering
  - name: TerraformResource
    description: Contains endpoints related to Terraform deployment operations
  - name: ValidationResource
    description: Contains all endpoints related to both data validation and its further retrieval.
  - name: InfoResource
    description: Contains all endpoints related to general info of API Server.
  - name: HealthCheckResource
    description: ""

paths:
  /v1/topic/logs:
    get:
      tags:
        - TopicResource
      responses:
        200:
          description: Current resource state is successfully retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TopicLogsResult"
        500:
          description: Kafka service is not available
  /v1/terraform/apply:
    post:
      tags:
        - TerraformResource
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TerraformDeploymentApplication"
      responses:
        201:
          description: New remote infrastructure was successfully deployed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TerraformDeploymentApplicationResult"
        400:
          description: Given deployment application contains incorrect data
  /v1/terraform/destroy:
    post:
      tags:
        - TerraformResource
      requestBody:
        required: true
        description: Destroys new Terraform infrastructure
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TerraformDestructionApplication"
      responses:
        201:
          description: Deployed remote infrastructure is successfully destroyed
        400:
          description: Given destruction application contains incorrect data
  /v1/secrets/acquire:
    post:
      tags:
        - ValidationResource
      requestBody:
        required: true
        description: Checks if the given secrets file contains correct data
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/ValidationSecretsApplication"
      responses:
        201:
          description: Given secrets file is confirmed to be correct
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationSecretsApplicationResult"
        400:
          description: Given script application contains incorrect data
  /v1/script/acquire:
    post:
      tags:
        - ValidationResource
      requestBody:
        required: true
        description: Checks if the given script file contains allowed data
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/ValidationScriptApplication"
      responses:
        201:
          description: Given script file is confirmed to be correct
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationScriptApplicationResult"
        400:
          description: Given script application contains incorrect data
  /v1/info/version:
    get:
      tags:
        - InfoResource
      responses:
        200:
          description: General information about running API Server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationInfoResult"
  /v1/health:
    get:
      tags:
        - HealthCheckResource
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthCheckResult"
components:
  schemas:
    TopicLogsResult:
      required:
        - result
      properties:
        result:
          type: array
          items:
            $ref: "#/components/schemas/TopicLogsUnit"
    TopicLogsUnit:
      required:
        - id
        - data
        - error
        - hostname
        - hostaddress
        - timestamp
      properties:
        id:
          type: string
          format: uuid
        data:
          type: string
        error:
          type: string
        hostname:
          type: string
        hostaddress:
          type: string
        timestamp:
          type: string
          format: timestamp
    TerraformDeploymentApplication:
      required:
        - requests
        - provider
        - credentials
      properties:
        requests:
          type: array
          items:
            $ref: "#/components/schemas/DeploymentRequest"
        provider:
          $ref: "#/components/schemas/Provider"
        credentials:
          $ref: "#/components/schemas/CredentialsFields"
    DeploymentRequest:
      required:
        - name
        - script
        - frequency
      properties:
        name:
          type: string
        script:
          type: string
        frequency:
          type: string
          pattern: "(((([0-9]|[0-5][0-9])(-([0-9]|[0-5][0-9]))?,)*([0-9]|[0-5][0-9])(-([0-9]|[0-5][0-9]))?)|(([\\*]|[0-9]|[0-5][0-9])/([0-9]|[0-5][0-9]))|([\\?])|([\\*]))[\\s](((([0-9]|[0-5][0-9])(-([0-9]|[0-5][0-9]))?,)*([0-9]|[0-5][0-9])(-([0-9]|[0-5][0-9]))?)|(([\\*]|[0-9]|[0-5][0-9])/([0-9]|[0-5][0-9]))|([\\?])|([\\*]))[\\s](((([0-9]|[0-1][0-9]|[2][0-3])(-([0-9]|[0-1][0-9]|[2][0-3]))?,)*([0-9]|[0-1][0-9]|[2][0-3])(-([0-9]|[0-1][0-9]|[2][0-3]))?)|(([\\*]|[0-9]|[0-1][0-9]|[2][0-3])/([0-9]|[0-1][0-9]|[2][0-3]))|([\\?])|([\\*]))[\\s](((([1-9]|[0][1-9]|[1-2][0-9]|[3][0-1])(-([1-9]|[0][1-9]|[1-2][0-9]|[3][0-1]))?,)*([1-9]|[0][1-9]|[1-2][0-9]|[3][0-1])(-([1-9]|[0][1-9]|[1-2][0-9]|[3][0-1]))?(C)?)|(([1-9]|[0][1-9]|[1-2][0-9]|[3][0-1])/([1-9]|[0][1-9]|[1-2][0-9]|[3][0-1])(C)?)|(L(-[0-9])?)|(L(-[1-2][0-9])?)|(L(-[3][0-1])?)|(LW)|([1-9]W)|([1-3][0-9]W)|([\\?])|([\\*]))[\\s](((([1-9]|0[1-9]|1[0-2])(-([1-9]|0[1-9]|1[0-2]))?,)*([1-9]|0[1-9]|1[0-2])(-([1-9]|0[1-9]|1[0-2]))?)|(([1-9]|0[1-9]|1[0-2])/([1-9]|0[1-9]|1[0-2]))|(((JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)(-(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC))?,)*(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)(-(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC))?)|((JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)/(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC))|([\\?])|([\\*]))[\\s]((([1-7](-([1-7]))?,)*([1-7])(-([1-7]))?)|([1-7]/([1-7]))|(((MON|TUE|WED|THU|FRI|SAT|SUN)(-(MON|TUE|WED|THU|FRI|SAT|SUN))?,)*(MON|TUE|WED|THU|FRI|SAT|SUN)(-(MON|TUE|WED|THU|FRI|SAT|SUN))?(C)?)|((MON|TUE|WED|THU|FRI|SAT|SUN)/(MON|TUE|WED|THU|FRI|SAT|SUN)(C)?)|(([1-7]|(MON|TUE|WED|THU|FRI|SAT|SUN))?(L|LW)?)|(([1-7]|MON|TUE|WED|THU|FRI|SAT|SUN)#([1-7])?)|([\\?])|([\\*]))([\\s]?(([\\*])?|(19[7-9][0-9])|(20[0-9][0-9]))?| (((19[7-9][0-9])|(20[0-9][0-9]))/((19[7-9][0-9])|(20[0-9][0-9])))?| ((((19[7-9][0-9])|(20[0-9][0-9]))(-((19[7-9][0-9])|(20[0-9][0-9])))?,)*((19[7-9][0-9])|(20[0-9][0-9]))(-((19[7-9][0-9])|(20[0-9][0-9])))?)?)"
    Provider:
      type: string
      enum:
        - aws
    TerraformDeploymentApplicationResult:
      required:
        - machineAddress
      properties:
        machineAddress:
          type: string
    TerraformDestructionApplication:
      required:
        - requests
        - provider
        - credentials
      properties:
        requests:
          type: array
          items:
            $ref: "#/components/schemas/DestructionRequest"
        provider:
          $ref: "#/components/schemas/Provider"
        credentials:
          $ref: "#/components/schemas/CredentialsFields"

    CredentialsFields:
      anyOf:
        - $ref: "#/components/schemas/AWSCredentials"
        - $ref: "#/components/schemas/GCPCredentials"

    AWSCredentials:
      required:
        - secrets
        - region
      properties:
        secrets:
          $ref: "#/components/schemas/AWSSecrets"
        region:
          type: string
    AWSSecrets:
      required:
        - accessKey
        - secretKey
      properties:
        accessKey:
          type: string
        secretKey:
          type: string

    GCPCredentials:
      required:
        - key
      properties:
        key:
          type: string



#    CredentialsFields:
#      type: object
#      properties:
#        credentialsType:
#          type: string
#          enum: [ AWS, GCP ]
#      discriminator:
#        propertyName: credentialsType
#        mapping:
#          AWS: '#/components/schemas/AWSCredentials'
#          GCP: '#/components/schemas/GCPCredentials'
#      #---------------------------------------------------------------------------
#      # Concrete classes
#      #---------------------------------------------------------------------------
#    AWSCredentials:
#      allOf:
#        - $ref: "#/components/schemas/CredentialsFields"
#        - type: object
#          properties:
#              accessKey:
#                type: string
#    GCPCredentials:
#      allOf:
#        - $ref: "#/components/schemas/CredentialsFields"
#        - type: object
#          properties:
#            key:
#              type: string
#
#








    DestructionRequest:
      required:
        - name
      properties:
        name:
          type: string
    ValidationSecretsApplication:
      required:
        - provider
        - file
      properties:
        provider:
          $ref: "#/components/schemas/Provider"
        file:
          type: string
          format: binary
    ValidationSecretsApplicationResult:
      required:
        - valid
        - credentials
      properties:
        valid:
          type: boolean
        secrets:
          oneOf:
            - $ref: "#/components/schemas/AWSSecrets"
    ValidationScriptApplication:
      required:
        - file
      type: object
      properties:
        file:
          type: array
          items:
            type: string
            format: binary
    ValidationScriptApplicationResult:
      required:
        - valid
        - data
      properties:
        valid:
          type: boolean
        data:
          type: array
          items:
            type: string
    ApplicationInfoResult:
      properties:
        externalApi:
          $ref: "#/components/schemas/ApplicationExternalApiInfoResult"
    ApplicationExternalApiInfoResult:
      required:
        - version
        - hash
      properties:
        version:
          type: string
        hash:
          type: string
    HealthCheckResult:
      required:
        - status
        - checks
      properties:
        status:
          $ref: "#/components/schemas/HealthCheckStatus"
        checks:
          type: array
          items:
            $ref: "#/components/schemas/HealthCheckUnit"
    HealthCheckUnit:
      required:
        - name
        - status
      properties:
        name:
          type: string
        status:
          $ref: "#/components/schemas/HealthCheckStatus"
    HealthCheckStatus:
      type: string
      enum:
        - UP
        - DOWN