spring:
  main:
    banner-mode: off
    web-application-type: NONE


public static final String TERRAFORM_CONFIG_FILES_PATH = HOME_FOLDER_PATH.concat("tf");
public static final String TERRAFORM_CONTEXT_VAR = "resourcetracker_context";
public static final String TERRAFORM_BACKEND_CONFIG_SHARED_CREDENTIALS_FILE = "shared_credentials_file";
public static final String TERRAFORM_BACKEND_PROFILE = "profile";
public static final String TERRAFORM_BACKEND_STORAGE_ACCOUNT  = "storage_account";
public static final String TERRAFORM_BACKEND_CONTAINER_NAME  = "container_name";
public static final String TERRAFORM_BACKEND_SUBSCRIPTION_ID  = "subscription_id";
public static final String TERRAFORM_BACKEND_TENANT_ID  = "tenant_id";


public static final String AWS_SHARED_CREDENTIALS_FILE = "AWS_SHARED_CREDENTIALS_FILE";
public static final String AWS_PROFILE = "AWS_PROFILE";
public static final String AWS_REGION = "AWS_REGION";

