openapi: 3.0.1
info:
  title: Static OpenAPI document of ResourceTracker API Server
  description: ResourceTracker API Server Open API documentation
  version: "1.0"

paths:
  /v1/state:
    get:
      tags:
        - StateResource
      responses:
        200:
          description: Current resource state is successfully retrieved
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/ResourceState"
  /v1/terraform/apply:
    post:
      tags:
        - TerraformResource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TerraformDeploymentApplication'
      responses:
        201:
          description: New remote intrustructure was successfully deployed
        400:
          description: Given deployment application contains incorrect data
  /v1/terraform/destroy:
    post:
      tags:
        - TerraformResource
      requestBody:
        description: Destroys new terraform infrastructure
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TerraformDestructionApplication'
      responses:
        201:
          description: Deployed remote infrustructure is succcessfully destroyed
components:
  schemas:
    ResourceState:
      properties:
        logs:
          type: array
          items:
            type: string
    TerraformDeploymentApplication:
      properties:
        requests:
          type: array
          items:
            $ref: "#/components/schemas/Request"
    Request:
      properties:
        name:
          type: string
        script:
          type: string
        frequency:
          type: string
        provider:
          $ref: "#/components/schemas/Provider"
        credentials:
          oneOf:
            - $ref: '#/components/schemas/AWSCredentials'
    Provider:
      type: string
      enum:
        - aws
    AWSCredentials:
      properties:
        access_key:
          type: string
        secret_key:
          type: string
        profile:
          type: string
        region:
          type: string
    TerraformDestructionApplication:
      properties:
        name:
          type: array
          items:
            type: string