name: Terraform validation

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6
      - name: "Run deployment validation"
        run: |
          terraform validate -chdir="cli/src/main/resources/tf"

